services:
  - type: web
    name: feedbackpro-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
